name: build-one.yml

on:
  workflow_call:
    inputs:
      platform:
        description: 'Docker Linux platform, e.g. amd64.'
        required: true
        type: string
      runs-on:
        description: 'GitHub Actions runner to use, e.g. ubuntu-latest.'
        required: true
        type: string
        default: 'ubuntu-latest'
      rversion:
        description: 'R version number or next or devel'
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    name: ${{ inputs.rversion }}-${{ inputs.platform }}

    steps:
    - uses: actions/checkout@v6

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v6
      with:
        platforms: linux/${{ inputs.platform }}
        provenance: false
        push: false
        load: true
        build-args: |
          R_VERSION=${{ inputs.rversion }}
        tags: rhub/r-minimal:test

    - name: Calculate tags
      run: |
        cp -r tools /tmp
        docker run -v /tmp/tools:/tools \
          rhub/r-minimal:test \
          bash -c "/tools/calculate_tags.sh ${{ inputs.rversion }}" \
          | tail -1 > tags.txt
        cat tags.txt
      shell: bash

    - name: Push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/${{ inputs.platform }}
        provenance: false
        push: true
        build-args: |
          R_VERSION=${{ inputs.rversion }}
        tags: "ghcr.io/r-hub/r-minimal/r-minimal:${{ inputs.rversion }}-${{ inputs.platform }}"

    - name: Upload tags
      uses: actions/upload-artifact@v4
      with:
        name: tags-${{ inputs.rversion }}-${{ inputs.platform }}
        path: tags.txt
